
spring:
    datasource:
        url: jdbc:h2:~/forum
        driverClassName: org.h2.Driver
        username: sa
        password: 
    jpa:
        hibernate:            
            database-platform: org.hibernate.dialect.H2Dialect
            show-sql: true
            ddl-auto: update
    h2: 
        spring:
            
            h2-console-enabled: true
            h2-console-path: /h2-console