
spring:
    datasource:
        url: jdbc:h2:~/forum
        driverClassName: org.h2.Driver
        username: sa
        password: 
    jpa:
        hibernate:            
            database-platform: org.hibernate.dialect.H2Dialect
            show-sql: true
            ddl-auto: update
    h2: 
        spring:
            h2-console-enabled: true
            h2-console-path: /h2-console
forum:
    jwt:
        secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
        expiration: 86400000

# actuator
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "health,info"
                exclude: "env,beans"

    endpoint:
        info:
            enabled: true

info:
    app:
        name: "demo"
        version: "0.0.1-SNAPSHOT"
    encoding: "UTF-8"
    java:
        source: "11.0.8"
        target: "11.0.8"  